server {
    listen 80; 
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # إضافة رؤوس أمان تسمح بالاتصال بخدمات خارجية ضرورية
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://upload-widget.cloudinary.com https://widget.cloudinary.com https://js.stripe.com; connect-src 'self' https://api.cloudinary.com https://api.stripe.com https://airbnb-backend-production-7ed2.up.railway.app; img-src 'self' https://res.cloudinary.com data:; frame-src 'self' https://js.stripe.com;";
    }
}